from .. import SupportsAddMineServicerToServer as _SupportsAddMineServicerToServer

class MineStub(object): ...
class MineServicer(object): ...

add_MineServicer_to_server: _SupportsAddMineServicerToServer
