# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mine.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmine.proto\x12\x04Mine\"\x1c\n\x0f\x46izzBuzzRequest\x12\t\n\x01i\x18\x01 \x01(\x05\"\x1d\n\x10\x46izzBuzzResponse\x12\t\n\x01s\x18\x01 \x01(\t\"\x19\n\x0c\x43ountRequest\x12\t\n\x01n\x18\x01 \x01(\r\"\x1a\n\rCountResponse\x12\t\n\x01i\x18\x01 \x01(\r2u\n\x04Mine\x12\x39\n\x08\x46izzBuzz\x12\x15.Mine.FizzBuzzRequest\x1a\x16.Mine.FizzBuzzResponse\x12\x32\n\x05\x43ount\x12\x12.Mine.CountRequest\x1a\x13.Mine.CountResponse0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mine_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FIZZBUZZREQUEST._serialized_start=20
  _FIZZBUZZREQUEST._serialized_end=48
  _FIZZBUZZRESPONSE._serialized_start=50
  _FIZZBUZZRESPONSE._serialized_end=79
  _COUNTREQUEST._serialized_start=81
  _COUNTREQUEST._serialized_end=106
  _COUNTRESPONSE._serialized_start=108
  _COUNTRESPONSE._serialized_end=134
  _MINE._serialized_start=136
  _MINE._serialized_end=253
# @@protoc_insertion_point(module_scope)
